[package]
categories.workspace = true
description = "Graphs for GKR"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "gkr-graph"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ark-std.workspace = true
ff.workspace = true
ff_ext = { path = "../ff_ext" }
gkr = { path = "../gkr", features = ["parallel"] }
goldilocks.workspace = true
itertools.workspace = true
multilinear_extensions = { version = "0", path = "../multilinear_extensions" }
simple-frontend = { version = "0", path = "../simple-frontend" }
sumcheck = { version = "0", path = "../sumcheck" }
transcript = { version = "0", path = "../transcript" }
